[project]
name = "project"
version = "0.1.0"
requires-python = ">=3.12.0"
dependencies = [
  "kagglehub>=0.3.13",
  "matplotlib>=3.10.7",
  "numpy>=2.2.6",
  "opencv-python>=4.12.0.88",
  "pandas>=2.3.3",
  "pillow>=11.3.0",
  "torch>=2.7.0",
  "torchmetrics>=1.8.2",
  "torchvision>=0.22.0",
  "wandb>=0.23.0",
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]
torchvision = [
  { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
  { index = "pytorch-cu128", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
